services:
  - type: web
    name: intelligent-query-system
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: uvicorn run:app --host 0.0.0.0 --port 8000
    runtime: python
