runtime: python311

entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

instance_class: F2  # Free-tier eligible (1 shared CPU, 512 MB RAM)

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2

env_variables:
  # 🔑 Replace these with your actual keys or configs
OPENROUTER_API_KEY="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"
API_KEY="76ca443a60eca02027609610f76f0b4b9e6b16db3e3fab7752a9fb25593df0e9"
HUGGINGFACE_API_TOKEN="hf_kAOipyVHPRnMQdzgOxorxqVzFmJqIzmZC"
HOST="0.0.0.0"
# PORT="8000"
LOG_LEVEL="INFO"
LLM_MODEL="anthropic/claude-3-haiku"
EMBEDDING_MODEL="intfloat/e5-small"
